name: Auto Deploy after push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build, Deploy to S3 bucket and Invalidation chche CloudFront
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [14.15.x]

    steps:
      # 해당 레포지토리로 checkout 하는 Action 
      - uses: actions/checkout@v2

      # Node 환경을 설정하여 npm 커맨드를 사용할 수 있도록 하는 Action
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Github Repository Secrets 를 통해 환경 변수 파일을 생성합니다.
      # 리눅스 명령어 echo 는 인수로 받은 인수열을 >> 뒤에 있는 파일에 저장합니다.
      # 만약 파일이 존재하지 않는다면 파일을 생성한 후 문자열을 입력하게 됩니다.
     - name: "Create env file"
        run: |
          echo "REACT_APP_KAKAO_APPKEY=$REACT_APP_KAKAO_APPKEY" >> .env
          echo "REACT_APP_GOOGLE_CLIENTID=$REACT_APP_GOOGLE_CLIENTID" >> .env
          echo "REACT_APP_BASE_URL=$REACT_APP_BASE_URL" >> .env
          echo "REACT_APP_SOCKJS_URL=$REACT_APP_SOCKJS_URL" >> .env
        env:
          REACT_APP_KAKAO_APPKEY: ${{ secrets.REACT_APP_KAKAO_APPKEY }}
          REACT_APP_GOOGLE_CLIENTID: ${{ secrets.REACT_APP_GOOGLE_CLIENTID }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_SOCKJS_URL: ${{ secrets.REACT_APP_SOCKJS_URL }}

      - name: Npm install
        run: npm install 

      - name: Build
        run: npm run build

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_BUCKET_REGION }}
          SOURCE_DIR: "./build"

      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: "/*"
        continue-on-error: true
